import { IUnitUpsertData, upsertUnit } from "../services/unitService";
import { getBuildingType } from "../services/buildingTypeService";
import BuildingNames from "../constants/buildingNames";
import UnitNames from "../constants/unitsNames";
import TribeNames from "../constants/tribes";

const populateUnits = async (): Promise<void> => {
  console.log("start populating units");

  const units = [...(await getBaseGaulUnits()), ...getBaseNatureUnits()];
  for (const unit of units) {
    try {
      await upsertUnit(unit);
    } catch (error) {
      console.error(`Error upserting unit "${unit.name}":`, error);
    }
  }

  console.log("finish populating units");
};

const getBaseGaulUnits = async (): Promise<IUnitUpsertData[]> => {
  const barracks = await getBuildingType(BuildingNames.BARRACKS);
  const stable = await getBuildingType(BuildingNames.STABLE);
  const workshop = await getBuildingType(BuildingNames.WORKSHOP);
  const residence = await getBuildingType(BuildingNames.RESIDENCE);

  return [
    {
      name: UnitNames.PHALANX,
      tribe: TribeNames.GAULS,
      selector: "t1",
      building: barracks,
      att: 15,
      attC: 0,
      def: 40,
      defC: 50,
      wood: 100,
      clay: 130,
      iron: 55,
      crop: 30,
      upkeep: 1,
    },
    {
      name: UnitNames.SWORDSMAN,
      tribe: TribeNames.GAULS,
      selector: "t2",
      building: barracks,
      att: 65,
      attC: 0,
      def: 35,
      defC: 20,
      wood: 140,
      clay: 150,
      iron: 185,
      crop: 60,
      upkeep: 1,
    },
    {
      name: UnitNames.PATHFINDER,
      tribe: TribeNames.GAULS,
      selector: "t3",
      building: stable,
      att: 0,
      attC: 0,
      def: 20,
      defC: 10,
      wood: 170,
      clay: 150,
      iron: 20,
      crop: 40,
      upkeep: 2,
    },
    {
      name: UnitNames.THEUTATES_THUNDER,
      tribe: TribeNames.GAULS,
      selector: "t4",
      building: stable,
      att: 0,
      attC: 100,
      def: 25,
      defC: 40,
      wood: 350,
      clay: 450,
      iron: 230,
      crop: 60,
      upkeep: 2,
    },
    {
      name: UnitNames.DRUIDRIDER,
      tribe: TribeNames.GAULS,
      selector: "t5",
      building: stable,
      att: 0,
      attC: 45,
      def: 115,
      defC: 55,
      wood: 360,
      clay: 330,
      iron: 280,
      crop: 120,
      upkeep: 2,
    },
    {
      name: UnitNames.HAEDUAN,
      tribe: TribeNames.GAULS,
      selector: "t6",
      building: stable,
      att: 0,
      attC: 140,
      def: 60,
      defC: 165,
      wood: 500,
      clay: 620,
      iron: 675,
      crop: 170,
      upkeep: 3,
    },
    {
      name: UnitNames.RAM,
      tribe: TribeNames.GAULS,
      selector: "t7",
      building: workshop,
      att: 50,
      attC: 0,
      def: 30,
      defC: 105,
      wood: 950,
      clay: 555,
      iron: 330,
      crop: 75,
      upkeep: 3,
    },
    {
      name: UnitNames.TREBUCHET,
      tribe: TribeNames.GAULS,
      selector: "t8",
      building: workshop,
      att: 70,
      attC: 0,
      def: 45,
      defC: 10,
      wood: 960,
      clay: 1450,
      iron: 630,
      crop: 90,
      upkeep: 6,
    },
    {
      name: UnitNames.CHIEFTAIN,
      tribe: TribeNames.GAULS,
      selector: "t9",
      building: residence,
      att: 40,
      attC: 0,
      def: 50,
      defC: 50,
      wood: 30750,
      clay: 45400,
      iron: 31000,
      crop: 37500,
      upkeep: 4,
    },
    {
      name: UnitNames.SETTLER,
      tribe: TribeNames.GAULS,
      selector: "t10",
      building: residence,
      att: 0,
      attC: 0,
      def: 80,
      defC: 80,
      wood: 4400,
      clay: 5600,
      iron: 4200,
      crop: 3900,
      upkeep: 1,
    },
    {
      name: UnitNames.TRAPS,
      tribe: TribeNames.GAULS,
      selector: "t911",
      building: residence,
      att: 0,
      attC: 0,
      def: 0,
      defC: 0,
      wood: 35,
      clay: 30,
      iron: 10,
      crop: 20,
      upkeep: 0,
    },
  ];
};

const getBaseNatureUnits = (): IUnitUpsertData[] => {
  return [
    {
      name: UnitNames.RAT,
      tribe: TribeNames.NATURE,
      selector: "t1",
      building: null,
      att: 10,
      attC: 0,
      def: 25,
      defC: 20,
      wood: 40,
      clay: 40,
      iron: 40,
      crop: 40,
      upkeep: 1,
    },
    {
      name: UnitNames.SPIDER,
      tribe: TribeNames.NATURE,
      selector: "t2",
      building: null,
      att: 20,
      attC: 0,
      def: 35,
      defC: 40,
      wood: 40,
      clay: 40,
      iron: 40,
      crop: 40,
      upkeep: 1,
    },
    {
      name: UnitNames.SNAKE,
      tribe: TribeNames.NATURE,
      selector: "t3",
      building: null,
      att: 60,
      attC: 0,
      def: 40,
      defC: 60,
      wood: 40,
      clay: 40,
      iron: 40,
      crop: 40,
      upkeep: 1,
    },
    {
      name: UnitNames.BAT,
      tribe: TribeNames.NATURE,
      selector: "t4",
      building: null,
      att: 80,
      attC: 0,
      def: 66,
      defC: 50,
      wood: 40,
      clay: 40,
      iron: 40,
      crop: 40,
      upkeep: 1,
    },
    {
      name: UnitNames.WILD_BOAR,
      tribe: TribeNames.NATURE,
      selector: "t5",
      building: null,
      att: 50,
      attC: 0,
      def: 70,
      defC: 33,
      wood: 80,
      clay: 80,
      iron: 80,
      crop: 80,
      upkeep: 2,
    },
    {
      name: UnitNames.WOLF,
      tribe: TribeNames.NATURE,
      selector: "t6",
      building: null,
      att: 100,
      attC: 0,
      def: 80,
      defC: 70,
      wood: 80,
      clay: 80,
      iron: 80,
      crop: 80,
      upkeep: 2,
    },
    {
      name: UnitNames.BEAR,
      tribe: TribeNames.NATURE,
      selector: "t7",
      building: null,
      att: 250,
      attC: 0,
      def: 140,
      defC: 200,
      wood: 120,
      clay: 120,
      iron: 120,
      crop: 120,
      upkeep: 3,
    },
    {
      name: UnitNames.CROCODILE,
      tribe: TribeNames.NATURE,
      selector: "t8",
      building: null,
      att: 450,
      attC: 0,
      def: 380,
      defC: 240,
      wood: 120,
      clay: 120,
      iron: 120,
      crop: 120,
      upkeep: 3,
    },
    {
      name: UnitNames.TIGER,
      tribe: TribeNames.NATURE,
      selector: "t9",
      building: null,
      att: 200,
      attC: 0,
      def: 170,
      defC: 250,
      wood: 120,
      clay: 120,
      iron: 120,
      crop: 120,
      upkeep: 3,
    },
    {
      name: UnitNames.ELEPHANT,
      tribe: TribeNames.NATURE,
      selector: "t10",
      building: null,
      att: 600,
      attC: 0,
      def: 440,
      defC: 520,
      wood: 200,
      clay: 200,
      iron: 200,
      crop: 200,
      upkeep: 5,
    },
  ];
};

export default populateUnits;
