const TRAVIAN_BASE = "https://ptr.x3.international.travian.com";
const TRAVIAN_FARM_LIST = `${TRAVIAN_BASE}/build.php?id=39&gid=16&tt=99`;
const TRAVIAN_HERO_ADVENTURES = `${TRAVIAN_BASE}/hero/adventures`;
const TRAVIAN_RESOURCES_VIEW = `${TRAVIAN_BASE}/dorf1.php`;
const TRAVIAN_BUILDING_VIEW = `${TRAVIAN_BASE}/dorf2.php`;
const TRAVIAN_BUILD_VIEW = `${TRAVIAN_BASE}/build.php`;
const TRAVIAN_TASK_VIEW = `${TRAVIAN_BASE}/tasks`;

module.exports = {
  TRAVIAN_BASE,
  TRAVIAN_FARM_LIST,
  TRAVIAN_HERO_ADVENTURES,
  TRAVIAN_RESOURCES_VIEW,
  TRAVIAN_BUILDING_VIEW,
  TRAVIAN_BUILD_VIEW,
  TRAVIAN_TASK_VIEW,
};
